/* eslint-disable jsx-a11y/alt-text */
'use client';

import React from 'react';
import { Document, Page, Text, View, StyleSheet, PDFDownloadLink, Image } from '@react-pdf/renderer';
import { EquipmentData } from '@/lib/compliance';

// Create styles
const styles = StyleSheet.create({
    page: {
        flexDirection: 'column',
        backgroundColor: '#FFFFFF',
        padding: 40,
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 2,
        borderBottomColor: '#10B981', // Emerald 500
        paddingBottom: 10,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#064E3B', // Emerald 900
        textAlign: 'center',
        marginBottom: 5,
    },
    subtitle: {
        fontSize: 12,
        color: '#047857', // Emerald 700
        textAlign: 'center',
        marginBottom: 20,
    },
    section: {
        margin: 10,
        padding: 10,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 4,
    },
    label: {
        fontSize: 10,
        color: '#6B7280',
        marginBottom: 2,
    },
    value: {
        fontSize: 14,
        color: '#111827',
        marginBottom: 10,
        fontWeight: 'bold',
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: 'center',
        color: '#9CA3AF',
        fontSize: 10,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        paddingTop: 10,
    },
    watermark: {
        position: 'absolute',
        top: 300,
        left: 0,
        right: 0,
        textAlign: 'center',
        color: '#F3F4F6',
        fontSize: 60,
        transform: 'rotate(-45deg)',
        zIndex: -1,
    },
    verifBox: {
        marginTop: 20,
        padding: 10,
        backgroundColor: '#F9FAFB',
        borderWidth: 1,
        borderColor: '#D1D5DB',
    },
    hash: {
        fontFamily: 'Courier',
        fontSize: 10,
        color: '#374151',
    }
});

type Props = {
    data: EquipmentData;
};

const CertificateDocument = ({ data }: Props) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>REBATEGUARD</Text>
                <Text style={styles.subtitle}>Eligibility Compliance Certificate</Text>
            </View>

            <Text style={styles.watermark}>
                {data.region === 'Canada' ? 'VALID FOR REBATE' : 'REGIONAL'}
            </Text>

            <View style={styles.section}>
                <Text style={{ fontSize: 16, marginBottom: 10, color: '#047857' }}>Equipment Details</Text>

                <Text style={styles.label}>Outdoor Unit Model</Text>
                <Text style={styles.value}>{data.searchedOutdoorModel}</Text>

                <Text style={styles.label}>Indoor Unit Model</Text>
                <Text style={styles.value}>{data.searchedIndoorModel}</Text>

                <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
                    <View>
                        <Text style={styles.label}>SEER2 Rating</Text>
                        <Text style={styles.value}>{data.seer2}</Text>
                    </View>
                    <View>
                        <Text style={styles.label}>HSPF2 Rating</Text>
                        <Text style={styles.value}>{data.hspf2}</Text>
                    </View>
                    <View>
                        <Text style={styles.label}>Region</Text>
                        <Text style={styles.value}>{data.region}</Text>
                    </View>
                </View>
            </View>

            <View style={styles.verifBox}>
                <Text style={styles.label}>Verification ID (Hash)</Text>
                <Text style={styles.hash}>
                    {Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15)}
                </Text>
                <Text style={styles.label}>Timestamp</Text>
                <Text style={styles.hash}>{new Date().toISOString()}</Text>
                <Text style={[styles.label, { marginTop: 10 }]}>Status</Text>
                <Text style={{ color: '#059669', fontWeight: 'bold' }}>COMPLIANT</Text>
            </View>

            <View style={styles.footer}>
                <Text>Generated by RebateGuard Compliance Engine</Text>
                <Text>This document certifies that the equipment specified above meets the efficiency criteria at the time of verification.</Text>
            </View>
        </Page>
    </Document>
);

export default function CertificateGenerator({ data }: Props) {
    return (
        <div className="mt-4">
            <PDFDownloadLink document={<CertificateDocument data={data} />} fileName="RebateGuard_Certificate.pdf">
                {({ blob, url, loading, error }) => (
                    <button
                        className={`w-full py-3 px-6 rounded-lg font-semibold shadow-lg transition-all ${loading
                                ? 'bg-gray-300 text-gray-500 cursor-wait'
                                : 'bg-emerald-600 hover:bg-emerald-700 text-white shadow-emerald-500/30'
                            }`}
                        disabled={loading}
                    >
                        {loading ? 'Generating Certificate...' : 'Download Official Certificate'}
                    </button>
                )}
            </PDFDownloadLink>
        </div>
    );
}
